#makefile для threads_for_count_ones_in_a_segment.c
threads_for_count_ones_in_a_segment: threads_for_count_ones_in_a_segment.c
	gcc  -Wall -Wextra -Wpedantic -o threads_for_count_ones_in_a_segment threads_for_count_ones_in_a_segment.c -lpthread -lrt

