#makefile для use_pthread_barrier_t___example1.c
use_pthread_barrier_t___example1: use_pthread_barrier_t___example1.c
	gcc  -Wall -Wextra -Wpedantic -o use_pthread_barrier_t___example1 use_pthread_barrier_t___example1.c -lpthread -lrt -no-pie
	

