#makefile для use_thread_local_storage.c
use_thread_local_storage: use_thread_local_storage.c
	gcc  -Wall -Wextra -Wpedantic -o use_thread_local_storage use_thread_local_storage.c -lpthread -lrt -no-pie
	

