#makefile для use_thread_specific_data.c
use_thread_specific_data: use_thread_specific_data.c
	gcc  -Wall -Wextra -Wpedantic -o use_thread_specific_data use_thread_specific_data.c -lpthread -lrt -no-pie
	

