#makefile для getting_the_thread_exit_code.c
getting_the_thread_exit_code: getting_the_thread_exit_code.c
	gcc  -Wall -Wextra -Wpedantic -o getting_the_thread_exit_code getting_the_thread_exit_code.c -lpthread -lrt -no-pie
	

