#makefile для use_pthread_mutex_timedlock.c
signal_for_pool: use_pthread_mutex_timedlock.c
	gcc  -Wall -Wextra -Wpedantic -o use_pthread_mutex_timedlock use_pthread_mutex_timedlock.c -lpthread -lrt -no-pie

