#makefile для incorrect_use_of_function_argument_pthread_exit.c
incorrect_use_of_function_argument_pthread_exit: incorrect_use_of_function_argument_pthread_exit.c
	gcc  -Wall -Wextra -Wpedantic -o incorrect_use_of_function_argument_pthread_exit incorrect_use_of_function_argument_pthread_exit.c -lpthread -lrt -no-pie
	

